// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.0
// source: kotlin/protobuf/kotlin_parser_service.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_kotlin_protobuf_kotlin_parser_service_proto protoreflect.FileDescriptor

var file_kotlin_protobuf_kotlin_parser_service_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x6b, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x6b, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x5f, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x1a, 0x23, 0x6b, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6b, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x5f,
	0x70, 0x61, 0x72, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0xb2, 0x01, 0x0a,
	0x0c, 0x4b, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x12, 0x53, 0x0a,
	0x10, 0x50, 0x61, 0x72, 0x73, 0x65, 0x4b, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x46, 0x69, 0x6c, 0x65,
	0x73, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4b, 0x6f, 0x74,
	0x6c, 0x69, 0x6e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4b, 0x6f, 0x74, 0x6c,
	0x69, 0x6e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x4a, 0x61, 0x76, 0x61, 0x46,
	0x69, 0x6c, 0x65, 0x73, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x4a, 0x61, 0x76, 0x61, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4a, 0x61, 0x76,
	0x61, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x67, 0x0a, 0x2f, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x73, 0x72, 0x6d, 0x6f, 0x63, 0x68, 0x65, 0x72, 0x2e, 0x67, 0x61, 0x7a, 0x65, 0x6c, 0x6c, 0x65,
	0x5f, 0x6b, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2e, 0x6b, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x70, 0x61,
	0x72, 0x73, 0x65, 0x72, 0x50, 0x01, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x73, 0x72, 0x6d, 0x6f, 0x63, 0x68, 0x65, 0x72, 0x2f, 0x67, 0x61, 0x7a, 0x65,
	0x6c, 0x6c, 0x65, 0x2d, 0x6b, 0x6f, 0x74, 0x6c, 0x69, 0x6e, 0x2f, 0x6b, 0x6f, 0x74, 0x6c, 0x69,
	0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var file_kotlin_protobuf_kotlin_parser_service_proto_goTypes = []interface{}{
	(*KotlinParserRequest)(nil),  // 0: protobuf.KotlinParserRequest
	(*JavaParserRequest)(nil),    // 1: protobuf.JavaParserRequest
	(*KotlinParserResponse)(nil), // 2: protobuf.KotlinParserResponse
	(*JavaParserResponse)(nil),   // 3: protobuf.JavaParserResponse
}
var file_kotlin_protobuf_kotlin_parser_service_proto_depIdxs = []int32{
	0, // 0: protobuf.KotlinParser.ParseKotlinFiles:input_type -> protobuf.KotlinParserRequest
	1, // 1: protobuf.KotlinParser.ParseJavaFiles:input_type -> protobuf.JavaParserRequest
	2, // 2: protobuf.KotlinParser.ParseKotlinFiles:output_type -> protobuf.KotlinParserResponse
	3, // 3: protobuf.KotlinParser.ParseJavaFiles:output_type -> protobuf.JavaParserResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kotlin_protobuf_kotlin_parser_service_proto_init() }
func file_kotlin_protobuf_kotlin_parser_service_proto_init() {
	if File_kotlin_protobuf_kotlin_parser_service_proto != nil {
		return
	}
	file_kotlin_protobuf_kotlin_parser_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kotlin_protobuf_kotlin_parser_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kotlin_protobuf_kotlin_parser_service_proto_goTypes,
		DependencyIndexes: file_kotlin_protobuf_kotlin_parser_service_proto_depIdxs,
	}.Build()
	File_kotlin_protobuf_kotlin_parser_service_proto = out.File
	file_kotlin_protobuf_kotlin_parser_service_proto_rawDesc = nil
	file_kotlin_protobuf_kotlin_parser_service_proto_goTypes = nil
	file_kotlin_protobuf_kotlin_parser_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// KotlinParserClient is the client API for KotlinParser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KotlinParserClient interface {
	ParseKotlinFiles(ctx context.Context, in *KotlinParserRequest, opts ...grpc.CallOption) (*KotlinParserResponse, error)
	ParseJavaFiles(ctx context.Context, in *JavaParserRequest, opts ...grpc.CallOption) (*JavaParserResponse, error)
}

type kotlinParserClient struct {
	cc grpc.ClientConnInterface
}

func NewKotlinParserClient(cc grpc.ClientConnInterface) KotlinParserClient {
	return &kotlinParserClient{cc}
}

func (c *kotlinParserClient) ParseKotlinFiles(ctx context.Context, in *KotlinParserRequest, opts ...grpc.CallOption) (*KotlinParserResponse, error) {
	out := new(KotlinParserResponse)
	err := c.cc.Invoke(ctx, "/protobuf.KotlinParser/ParseKotlinFiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kotlinParserClient) ParseJavaFiles(ctx context.Context, in *JavaParserRequest, opts ...grpc.CallOption) (*JavaParserResponse, error) {
	out := new(JavaParserResponse)
	err := c.cc.Invoke(ctx, "/protobuf.KotlinParser/ParseJavaFiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KotlinParserServer is the server API for KotlinParser service.
type KotlinParserServer interface {
	ParseKotlinFiles(context.Context, *KotlinParserRequest) (*KotlinParserResponse, error)
	ParseJavaFiles(context.Context, *JavaParserRequest) (*JavaParserResponse, error)
}

// UnimplementedKotlinParserServer can be embedded to have forward compatible implementations.
type UnimplementedKotlinParserServer struct {
}

func (*UnimplementedKotlinParserServer) ParseKotlinFiles(context.Context, *KotlinParserRequest) (*KotlinParserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseKotlinFiles not implemented")
}
func (*UnimplementedKotlinParserServer) ParseJavaFiles(context.Context, *JavaParserRequest) (*JavaParserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseJavaFiles not implemented")
}

func RegisterKotlinParserServer(s *grpc.Server, srv KotlinParserServer) {
	s.RegisterService(&_KotlinParser_serviceDesc, srv)
}

func _KotlinParser_ParseKotlinFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KotlinParserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KotlinParserServer).ParseKotlinFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.KotlinParser/ParseKotlinFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KotlinParserServer).ParseKotlinFiles(ctx, req.(*KotlinParserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KotlinParser_ParseJavaFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JavaParserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KotlinParserServer).ParseJavaFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.KotlinParser/ParseJavaFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KotlinParserServer).ParseJavaFiles(ctx, req.(*JavaParserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _KotlinParser_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.KotlinParser",
	HandlerType: (*KotlinParserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ParseKotlinFiles",
			Handler:    _KotlinParser_ParseKotlinFiles_Handler,
		},
		{
			MethodName: "ParseJavaFiles",
			Handler:    _KotlinParser_ParseJavaFiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kotlin/protobuf/kotlin_parser_service.proto",
}
